ARG VARIANT="16-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-${VARIANT}

ENV MONGO_URI=localhost:27017
ENV DOMAIN=http://localhost:1337
ENV FRONTEND_DOMAIN=http://localhost:3000
